// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncujmwhapcadecijolnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jdWptd2hhcGNhZGVjaWpvbG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4Njc2MzEsImV4cCI6MjA2NDQ0MzYzMX0.QAVwYcCIBSqC4omcMhpxRSm6Z7f9d5pCZ-bLePwDTx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);